version: '3.8'

services:
  bekbook-backend:
    build:
      context: .
      dockerfile: artifacts/api-server/Dockerfile
    container_name: bekbook-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:alif24_secure_password@alif24-postgres:5432/alif24
      - JWT_SECRET=alif24_jwt_secret_key
      - PORT=8007
    ports:
      - "127.0.0.1:8007:8007"
    networks:
      - alif24-network

  bekbook-frontend:
    build:
      context: .
      dockerfile: artifacts/mahalla-kutubxona/Dockerfile
    container_name: bekbook-frontend
    restart: always
    ports:
      - "5180:80"
    networks:
      - alif24-network

networks:
  alif24-network:
    name: alif-24_alif24-network
    external: true
